name: Build and deploy to pre-prod
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install and Build
        run: |
          npm install
          npm run build
          touch out/.nojekyll

      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.5.7
        with:
          SSH: true
          REPOSITORY_NAME: highfieldhouse/website-pre-prod-gh-pages
          BRANCH: gh-pages
          FOLDER: out
          CLEAN: true
          CLEAN_EXCLUDE: '[".nojekyll", "CNAME"]'
